version: "3"

services:
  db:
    container_name: store_manager_db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./migration.sql:/docker-entrypoint-initdb.d/migration.sql
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql

    ports:
      - 3306:3306


